### PR TITLE
Patch blueprint css deletion

### PR DESCRIPTION
**Pull request by fcollonval**

### CODE REVIEW

**Comment by fcollonval** [comment]
please update snapshots

**Comment by fcollonval** [comment]
please update snapshots

**Comment by fcollonval** [comment]
please update snapshots

**Comment by fcollonval** [comment]
@echarles I updated the PR to fix the style on the launcher cards. I see now some troubles due to the focus outline (weirdly it was not there before).

As I can't push directly on your PR, do you prefer me to open a PR against yours or to open a new one?

**Comment by echarles** [comment]
Thx a lot for working on this. It may be easier to open a brand new PR from your fork which also allows to regenerate the galata snapshots. If OK for your, just close this one and ping me from the new PR for me to review. Thx!

**Pull request closed without merging**
